# Generated by Django 4.2 on 2025-05-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.reservation'),
        ),
    ]
