# Generated by Django 4.2 on 2025-05-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_reservation_orders_order_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_amount',
        ),
    ]
