# Generated by Django 4.2 on 2025-05-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reservation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.IntegerField(default=60),
        ),
    ]
