# Generated by Django 4.2 on 2025-05-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
