# Generated by Django 4.2 on 2025-05-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reservation_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
