# Generated by Django 4.2 on 2025-05-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderitem_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
