# Generated by Django 4.2 on 2025-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
