# Generated by Django 4.2 on 2025-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orderitem_order_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
