# Generated by Django 4.2 on 2025-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_menu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_table',
            field=models.IntegerField(default=0),
        ),
    ]
